export const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p/";
export const DEFAULT_BG_COLOR = "#0a0a0f";

// Genres that work meaningfully across both movies and TV for the "Movies & Shows" filter.
// movieGenre / tvGenre are the values passed to TMDB's with_genres (pipe = OR).
export const COMBINED_GENRES = [
  {
    id: "action-adventure",
    name: "Action & Adventure",
    movieGenre: "28|12",
    tvGenre: 10759,
  },
  { id: "animation", name: "Animation", movieGenre: 16, tvGenre: 16 },
  { id: "anime", name: "Anime", movieGenre: "anime", tvGenre: "anime" },
  { id: "comedy", name: "Comedy", movieGenre: 35, tvGenre: 35 },
  { id: "crime", name: "Crime", movieGenre: 80, tvGenre: 80 },
  { id: "documentary", name: "Documentary", movieGenre: 99, tvGenre: 99 },
  { id: "drama", name: "Drama", movieGenre: 18, tvGenre: 18 },
  { id: "family", name: "Family", movieGenre: 10751, tvGenre: 10751 },
  { id: "mystery", name: "Mystery", movieGenre: 9648, tvGenre: 9648 },
  {
    id: "sci-fi-fantasy",
    name: "Sci-Fi & Fantasy",
    movieGenre: "878|14",
    tvGenre: 10765,
  },
  { id: "war", name: "War & Politics", movieGenre: 10752, tvGenre: 10768 },
  { id: "western", name: "Western", movieGenre: 37, tvGenre: 37 },
];

export const MOVIE_GENRES = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: "anime", name: "Anime" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 27, name: "Horror" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];

export const TV_GENRES = [
  { id: 10759, name: "Action & Adventure" },
  { id: 16, name: "Animation" },
  { id: "anime", name: "Anime" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 10762, name: "Kids" },
  { id: 9648, name: "Mystery" },
  { id: 10763, name: "News" },
  { id: 10764, name: "Reality" },
  { id: 10765, name: "Sci-Fi & Fantasy" },
  { id: 10766, name: "Soap" },
  { id: 10767, name: "Talk" },
  { id: 10768, name: "War & Politics" },
  { id: 37, name: "Western" },
];

export const RESOLUTIONS = [
  { label: "4K — 3840×2160", width: 3840, height: 2160 },
  { label: "1440p — 2560×1440", width: 2560, height: 1440 },
  { label: "1080p — 1920×1080", width: 1920, height: 1080 },
  { label: "720p — 1280×720", width: 1280, height: 720 },
];

export const TEXT_FONTS = [
  { value: "Anton", weight: 400 },
  { value: "Bebas Neue", weight: 400 },
  { value: "Cinzel", weight: 700 },
  { value: "DM Serif Display", weight: 400 },
  { value: "Inter", weight: 700 },
  { value: "Montserrat", weight: 800 },
  { value: "Oswald", weight: 600 },
  { value: "Playfair Display", weight: 700 },
  { value: "Raleway", weight: 700 },
  { value: "Roboto Condensed", weight: 700 },
];

export const WATCH_PROVIDERS = [
  { id: "8", name: "Netflix" },
  { id: "9", name: "Amazon Prime" },
  { id: "337", name: "Disney+" },
  { id: "1899", name: "HBO Max" },
  { id: "350", name: "Apple TV" },
  { id: "15", name: "Hulu" },
  { id: "2303|2616", name: "Paramount+" },
  { id: "386|387", name: "Peacock" },
  { id: "290", name: "Hallmark" },
  { id: "99", name: "Shudder" },
  { id: "520", name: "Discovery+" },
  { id: "190", name: "Curiosity Stream" },
  { id: "1956", name: "Angel Studios" },
  { id: "83", name: "The CW" },
  { id: "283", name: "Crunchyroll" },
  { id: "526", name: "AMC+" },
  { id: "43", name: "Starz" },
  { id: "209", name: "PBS" },
  { id: "34", name: "MGM+" },
  { id: "211", name: "Freeform" },
  { id: "156", name: "A&E" },
  { id: "157", name: "Lifetime" },
  { id: "151", name: "BritBox" },
  { id: "251", name: "ALLBLK" },
  { id: "278", name: "Pureflix" },
  { id: "318", name: "Adult Swim" },
  { id: "365", name: "Bravo" },
  { id: "412", name: "TLC" },
  { id: "406", name: "HGTV" },
  { id: "1964", name: "National Geographic" },
  { id: "155", name: "History Channel" },
];

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "ar", name: "Arabic" },
  { code: "zh", name: "Chinese" },
  { code: "da", name: "Danish" },
  { code: "nl", name: "Dutch" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "hi", name: "Hindi" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "no", name: "Norwegian" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "es", name: "Spanish" },
  { code: "sv", name: "Swedish" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
];

export const DECADES = [
  { value: 1960, label: "60s" },
  { value: 1970, label: "70s" },
  { value: 1980, label: "80s" },
  { value: 1990, label: "90s" },
  { value: 2000, label: "00s" },
  { value: 2010, label: "10s" },
  { value: 2020, label: "20s" },
];

export const FONT_WEIGHTS = {
  Inter: 700,
  "Bebas Neue": 400,
  Montserrat: 800,
  Oswald: 600,
  "Playfair Display": 700,
  "Roboto Condensed": 700,
};

export const TEXT_ANCHORS = {
  "top-left": { xFrac: 0, yFrac: 0, align: "left", baseline: "top" },
  "top-center": { xFrac: 0.5, yFrac: 0, align: "center", baseline: "top" },
  "top-right": { xFrac: 1, yFrac: 0, align: "right", baseline: "top" },
  "center-left": { xFrac: 0, yFrac: 0.5, align: "left", baseline: "middle" },
  center: { xFrac: 0.5, yFrac: 0.5, align: "center", baseline: "middle" },
  "center-right": { xFrac: 1, yFrac: 0.5, align: "right", baseline: "middle" },
  "bottom-left": { xFrac: 0, yFrac: 1, align: "left", baseline: "bottom" },
  "bottom-center": {
    xFrac: 0.5,
    yFrac: 1,
    align: "center",
    baseline: "bottom",
  },
  "bottom-right": { xFrac: 1, yFrac: 1, align: "right", baseline: "bottom" },
};

export const REGIONS = [
  { code: "AE", name: "United Arab Emirates" },
  { code: "AR", name: "Argentina" },
  { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" },
  { code: "BE", name: "Belgium" },
  { code: "BD", name: "Bangladesh" },
  { code: "BR", name: "Brazil" },
  { code: "CA", name: "Canada" },
  { code: "CH", name: "Switzerland" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DE", name: "Germany" },
  { code: "DK", name: "Denmark" },
  { code: "EG", name: "Egypt" },
  { code: "ES", name: "Spain" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GB", name: "United Kingdom" },
  { code: "GR", name: "Greece" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IL", name: "Israel" },
  { code: "IN", name: "India" },
  { code: "IT", name: "Italy" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "MX", name: "Mexico" },
  { code: "MY", name: "Malaysia" },
  { code: "NG", name: "Nigeria" },
  { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" },
  { code: "NZ", name: "New Zealand" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SE", name: "Sweden" },
  { code: "SG", name: "Singapore" },
  { code: "TH", name: "Thailand" },
  { code: "TR", name: "Turkey" },
  { code: "TW", name: "Taiwan" },
  { code: "US", name: "United States" },
  { code: "VN", name: "Vietnam" },
  { code: "ZA", name: "South Africa" },
];

export const MOVIE_SORT_OPTIONS = [
  { value: "popular", label: "Popular" },
  { value: "top_rated", label: "Top Rated" },
  { value: "now_playing", label: "Now Playing" },
  { value: "upcoming", label: "Upcoming" },
  { value: "trending_week", label: "Trending This Week" },
];

export const TV_SORT_OPTIONS = [
  { value: "popular", label: "Popular" },
  { value: "top_rated", label: "Top Rated" },
  { value: "on_the_air", label: "On Air This Week" },
  { value: "airing_today", label: "Airing Today" },
  { value: "trending_week", label: "Trending This Week" },
];
